# Generated by Django 5.2.3 on 2025-06-13 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_book_image_boookimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoookImage',
            new_name='BookImage',
        ),
    ]
